### ISSUE TITLE
SDK Kubernetes page contains links to a repo that no longer exists

### ISSUE THREAD

**Issue by alessandrolandi** [bitwarden/contributing-docs#334] opened 2024-04-12 02:25 UTC
### Page

https://contributing.bitwarden.com/getting-started/sdk/secrets-manager/integrations/kubernetes

### Expected Result

Redirect to sm-kubernetes repo 

### Actual Result

404 Page

### Additional Context

It looks like sm-kubernetes and sm-operator have been deprecated and replaced by Helm. If so, it seems like this page would need to be revised to reflect these changes.

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by alessandrolandi** [comment] 2024-04-12 02:28
If Bitwarden would like to make changes to this page to reflect the switch to Helm, I would love to submit my own pr with the changes following the instructions in this link https://bitwarden.com/help/self-host-with-helm/.

**Comment by differsthecat** [comment] 2024-04-24 14:35
Hi @alessandrolandi , thank you for the report!

The `sm-kubernetes` links are actually to a repository we have that will soon be public. 
We jumped the gun a bit on publishing this documentation, hence it is returning 404's. 

I will leave this open and close it as soon as we make that repo public.

**Comment by differsthecat** [comment] 2024-06-20 18:25
The [sm-kubernetes](https://github.com/bitwarden/sm-kubernetes) repo is public now, and the links are working as intended now 🙂

**Closed by differsthecat** 2024-06-20 18:25 UTC
Labels: bug
